#!/usr/bin/env bash

RUNS=50
INPUT_DATA='uf_inputdata_20000NOD_20000SEQ_1722048887.txt'
ALGS4_LIB="${HOME}/Developer/Repo/algs4/lib/algs4.jar"
ALGO_CLASS='WQUF.java'

total_runtime=0
for ((i=1; i<="${RUNS}"; i++)); do
  current_runtime="$(java -cp "${ALGS4_LIB}" ../java/${ALGO_CLASS} < "${INPUT_DATA}" | sed -E 's/^.*took ([0-9]+)ms$/\1/g')"
  echo "run $i took $current_runtime"
  ((total_runtime += current_runtime))
done

echo "total runtime = ${total_runtime}"
echo "average runtime = $((total_runtime / RUNS))"

exit 0
