#!/usr/bin/env bash

RUNS=150
INPUT_DATA='uf_inputdata_20000NOD_20000SEQ_1722048887.txt'
ALGS4_LIB="${HOME}/Developer/Repo/algs4/lib/algs4.jar"
ALGO_CLASS='WQURPCUF.java'

bar_size=40
bar_char_done="#"
bar_char_todo="-"
bar_percentage_scale=2
function show_progress {
    current="$1"
    total="$2"

    # calculate the progress in percentage
    percent=$(bc <<< "scale=$bar_percentage_scale; 100 * $current / $total" )
    # The number of done and todo characters
    done=$(bc <<< "scale=0; $bar_size * $percent / 100" )
    todo=$(bc <<< "scale=0; $bar_size - $done" )

    # build the done and todo sub-bars
    done_sub_bar=$(printf "%${done}s" | tr " " "${bar_char_done}")
    todo_sub_bar=$(printf "%${todo}s" | tr " " "${bar_char_todo}")

    # output the bar
    echo -ne "\rProgress : [${done_sub_bar}${todo_sub_bar}] ${percent}%"

    if [ $total -eq $current ]; then
      echo -e "\nDONE -- $(date)"
    fi
}

echo "starting [${RUNS}] runs for [${ALGO_CLASS}] algorithm now..."

total_runtime=0
for ((i=1; i<="${RUNS}"; i++)); do
  current_runtime="$(java -cp "${ALGS4_LIB}" ../java/${ALGO_CLASS} < "${INPUT_DATA}" | sed -E 's/^.*took ([0-9]+)ms$/\1/g')"
  ((total_runtime += current_runtime))
  show_progress "${i}" "${RUNS}"
done

echo "[${RUNS}] runs took [${total_runtime}ms]"
echo "average runtime is [$((total_runtime / RUNS))ms]"

exit 0
